import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FHeaderStyles headerStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FHeaderStyles(
  rootStyle: FHeaderStyle(
    systemOverlayStyle: colors.systemOverlayStyle,
    titleTextStyle: typography.xl3.copyWith(
      color: colors.foreground,
      fontWeight: FontWeight.w700,
      height: 1,
    ),
    actionStyle: _headerActionStyle(colors: colors, style: style, size: 30),
    padding: style.pagePadding.copyWith(bottom: 15),
  ),
  nestedStyle: FHeaderStyle(
    systemOverlayStyle: colors.systemOverlayStyle,
    titleTextStyle: typography.xl.copyWith(
      color: colors.foreground,
      fontWeight: FontWeight.w600,
      height: 1,
    ),
    actionStyle: _headerActionStyle(colors: colors, style: style, size: 25),
    padding: style.pagePadding.copyWith(bottom: 15),
  ),
);

FHeaderActionStyle _headerActionStyle({
  required FColors colors,
  required FStyle style,
  required double size,
}) => FHeaderActionStyle(
  iconStyle: FWidgetStateMap({
    WidgetState.disabled: IconThemeData(
      color: colors.disable(colors.foreground),
      size: size,
    ),
    WidgetState.any: IconThemeData(color: colors.foreground, size: size),
  }),
  focusedOutlineStyle: style.focusedOutlineStyle,
  tappableStyle: style.tappableStyle,
);
